//! A WASM/browser terminal backend, driven by pushed input and pulled ANSI output.
//!
//! [`TerminalWasm`] implements [`Backend`] directly (like
//! [`Headless`](retroglyph_core::backend::Headless)): there is no event loop
//! here. A browser terminal emulator (e.g. xterm.js -- this crate has no
//! dependency on it and no opinion about which one is used) is driven from
//! JS, which calls into this crate once per animation frame (or on demand)
//! to pull freshly rendered ANSI bytes and push back any input it collected.
//!
//! # Usage from Rust
//!
//! ```
//! use retroglyph_core::Terminal;
//! use retroglyph_terminal_wasm::TerminalWasm;
//!
//! let backend = TerminalWasm::new(80, 24);
//! let mut term = Terminal::new(backend);
//! term.put(0, 0, '@');
//! term.present().unwrap();
//! let ansi = term.backend_mut().take_output();
//! assert!(ansi.contains('@'));
//! ```
//!
//! # Usage from JS (via `wasm-bindgen`)
//!
//! The `wasm32` build additionally exposes free functions
//! (`wasm_terminal_new`, `wasm_terminal_resize`, `wasm_terminal_push_key`,
//! `wasm_terminal_take_output`, in this crate's `wasm` module -- only
//! compiled for `target_arch = "wasm32"`, so it won't appear in docs built
//! natively) that operate on an opaque handle, since
//! `retroglyph_core::event::Event` is not itself `wasm-bindgen`-compatible.
//!
//! The example below is a complete, working driver pairing this crate's
//! `wasm32` build with [xterm.js](https://xtermjs.org/) (any other browser
//! terminal emulator works the same way; this crate has no dependency on
//! xterm.js specifically). It assumes a `wasm-pack`/`wasm-bindgen`-generated
//! `./pkg.js` module built from a binary that re-exports this crate's `wasm`
//! module, and an `xterm.js` `<script>` already loaded on the page (see
//! [xterm.js's own quick start](https://xtermjs.org/docs/) for that half).
//!
//! It's a wiring template, not a full game: it plumbs input/output through
//! this crate's generic handle-based FFI but calls no per-frame drawing
//! logic of its own (that's the consumer's job, via their own Rust code
//! holding the `Terminal<TerminalWasm>` -- see "Usage from Rust" above). For
//! a complete, running example with an actual game loop, see the
//! `examples/` crate's [WASM demo gallery](https://crates-lurey-io.github.io/retroglyph/examples/)
//! linked from the workspace README; those demos use a different,
//! single-instance-per-page convenience FFI (`wasm_terminal_example_*`,
//! generated by `retroglyph_examples::wasm_entry!`) built on top of this
//! same `TerminalWasm` backend rather than the handle-based `wasm_terminal_*`
//! functions shown here.
//!
//! This file (kept in sync with the copy in `README.md` by
//! `readme_js_example_matches_canonical_driver` below) is
//! `crates/terminal-wasm/js/xterm-driver.js` in the source tree:
//!
//! ```js
#![doc = include_str!("../js/xterm-driver.js")]
//! ```

// Compile the code blocks in this crate's own README as doctests so its quick start is
// type-checked on every test run and cannot silently rot. The `cfg(doctest)` gate keeps this out
// of the rendered crate documentation -- see `retroglyph-crossterm`'s matching include for the
// same pattern applied to the workspace root README.
#[cfg(doctest)]
#[doc = include_str!("../README.md")]
struct ReadmeDoctests;

use retroglyph_core::backend::Backend;
use retroglyph_core::event::Event;
use retroglyph_core::grid::{Pos, Size};
use retroglyph_core::tile::Tile;
use retroglyph_terminal::TerminalRenderer;
use std::collections::VecDeque;
use std::time::Duration;

/// A [`Backend`] that renders into an in-memory ANSI byte buffer and accepts
/// pushed input, for driving a browser terminal emulator from WASM.
///
/// Unlike [`retroglyph_crossterm::Crossterm`](https://docs.rs/retroglyph-crossterm),
/// this backend:
///
/// - never queries a TTY for its size -- call [`resize`](Backend::resize) (or
///   [`Terminal::resize`](retroglyph_core::Terminal::resize)) whenever the
///   host reports a new size (e.g. from xterm.js's `fit` addon);
/// - never polls for input -- input only ever arrives via
///   [`push_event`](Backend::push_event), called from a `wasm-bindgen`
///   entry point in response to a JS event;
/// - buffers rendered ANSI bytes in memory rather than writing to a
///   descriptor; call [`take_output`](Self::take_output) once per animation
///   frame to drain them.
pub struct TerminalWasm {
    renderer: TerminalRenderer<Vec<u8>>,
    size: Size,
    event_queue: VecDeque<Event>,
}

impl TerminalWasm {
    /// Creates a new backend with the given initial size in cells.
    #[must_use]
    pub const fn new(width: u16, height: u16) -> Self {
        Self {
            renderer: TerminalRenderer::new(Vec::new()),
            size: Size { width, height },
            event_queue: VecDeque::new(),
        }
    }

    /// Injects a synthetic input event into the queue, to be returned by the
    /// next [`poll_event`](Backend::poll_event) call.
    ///
    /// Called from JS (via the `wasm-bindgen` entry points below) or from
    /// tests; not part of [`Backend`] itself beyond the no-op default.
    pub fn push_event(&mut self, event: Event) {
        self.event_queue.push_back(event);
    }

    /// Drains and returns the ANSI bytes rendered since the last call, as a
    /// UTF-8 string.
    ///
    /// Returns an empty string if nothing has been drawn since the last
    /// call. Call this once per animation frame from JS and write the result
    /// into the terminal emulator.
    ///
    /// # Panics
    ///
    /// Panics if the buffered output is not valid UTF-8. This can't happen
    /// through any safe, public API of this crate: [`TerminalRenderer`] only
    /// ever writes into its `Vec<u8>` writer via `write!`/`write_str` calls
    /// on ASCII escape sequences and glyphs encoded through `char`/`&str`
    /// (both always valid UTF-8), and this buffer is never exposed for
    /// direct mutation between a `take_output` call and the next `draw`. The
    /// only way to trigger this panic would be memory corruption or an
    /// `unsafe` write bypassing `TerminalRenderer` entirely -- and this
    /// workspace forbids `unsafe_code` outright, so no code in this crate
    /// (or its dependents, absent unsound external `unsafe`) can do that.
    #[must_use]
    pub fn take_output(&mut self) -> String {
        let bytes = std::mem::take(self.renderer.writer_mut());
        String::from_utf8(bytes)
            .expect("TerminalRenderer only ever writes valid UTF-8 via safe char/&str APIs")
    }
}

impl Backend for TerminalWasm {
    type Error = std::io::Error;

    fn draw<'a, I>(&mut self, content: I) -> Result<(), Self::Error>
    where
        I: Iterator<Item = (Pos, &'a Tile)>,
    {
        self.renderer.begin_synchronized_update()?;
        self.renderer.draw(content)
    }

    fn flush(&mut self) -> Result<(), Self::Error> {
        self.renderer.end_synchronized_update()?;
        self.renderer.flush()
    }

    fn size(&self) -> Size {
        self.size
    }

    fn resize(&mut self, size: Size) {
        self.size = size;
        // The host's terminal emulator clears/reflows on its own resize;
        // forget our tracked cursor/color state so the next draw() re-emits
        // full escape sequences instead of (incorrectly) skipping them.
        self.renderer.reset_state();
    }

    fn clear(&mut self) -> Result<(), Self::Error> {
        // Standard "clear screen, cursor home" CSI sequence: this backend has
        // no direct handle to the emulator, so clearing is just more ANSI
        // bytes for JS to forward, same as every other draw call.
        use std::io::Write as _;
        write!(self.renderer.writer_mut(), "\x1b[2J\x1b[H")?;
        self.renderer.reset_state();
        Ok(())
    }

    fn push_event(&mut self, event: Event) {
        Self::push_event(self, event);
    }

    fn poll_event(&mut self, _timeout: Duration) -> Option<Event> {
        // Never blocks: there is no runtime loop to block in. `_timeout` is
        // ignored, matching Headless's push-driven, non-blocking contract.
        self.event_queue.pop_front()
    }

    fn set_cursor_visible(&mut self, visible: bool) {
        let _ = write_cursor_visibility(&mut self.renderer, visible);
    }

    fn set_cursor_position(&mut self, position: Pos) {
        let _ = write_cursor_position(&mut self.renderer, position);
    }
}

fn write_cursor_visibility(
    renderer: &mut TerminalRenderer<Vec<u8>>,
    visible: bool,
) -> std::io::Result<()> {
    use std::io::Write as _;
    if visible {
        write!(renderer.writer_mut(), "\x1b[?25h")
    } else {
        write!(renderer.writer_mut(), "\x1b[?25l")
    }
}

/// Writes a CUP (Cursor Position) sequence, `CSI row;col H`, 1-indexed and
/// absolute.
///
/// This is the standard VT100/ANSI X3.64 (ECMA-48 `CUP`) cursor-positioning
/// sequence and is not one of the areas where browser terminal emulators
/// diverge: xterm.js (`CSI Ps ; Ps H`, `InputHandler.cursorPosition`, see
/// <https://xtermjs.org/docs/api/vtfeatures/> and
/// <https://github.com/xtermjs/xterm.js/blob/master/src/common/InputHandler.ts>)
/// and hterm/Terminalemulator (`CSI row ; col H`, `CUP`, see
/// <https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/docs/ControlSequences.md>)
/// both implement it identically, 1-indexed with default `[1, 1]` when
/// parameters are omitted, matching xterm's own `ctlseqs.txt` reference and
/// ECMA-48. No 0-indexed variant or alternate escape code was found in any
/// of these implementations, so no dual-emission fallback is needed here.
fn write_cursor_position(
    renderer: &mut TerminalRenderer<Vec<u8>>,
    position: Pos,
) -> std::io::Result<()> {
    use std::io::Write as _;
    write!(
        renderer.writer_mut(),
        "\x1b[{};{}H",
        position.y + 1,
        position.x + 1
    )
}

/// Decodes a `(code, mods)` pair from JS into a [`retroglyph_core::event::KeyEvent`].
///
/// `retroglyph_core::event::KeyCode`/`KeyModifiers` are not `wasm-bindgen`
/// FFI-safe types, so JS crosses the boundary with plain integers instead:
///
/// - `code`: for printable characters, the Unicode scalar value (as from
///   `event.key.codePointAt(0)` for a single-character key); for named keys,
///   one of [`key_codes`]'s constants (e.g. [`key_codes::LEFT`]).
/// - `mods`: a bitmask matching [`retroglyph_core::event::KeyModifiers`]'s
///   layout (`SHIFT = 1`, `CONTROL = 2`, `ALT = 4`, `SUPER = 8`). `SUPER` maps to the
///   JS `metaKey` (Cmd on macOS, the Windows/Super key elsewhere).
#[must_use]
pub fn decode_key_event(code: u32, mods: u8) -> Option<retroglyph_core::event::KeyEvent> {
    use key_codes as kc;
    use retroglyph_core::event::{KeyCode, KeyModifiers};

    let key_code = match code {
        kc::BACKSPACE => KeyCode::Backspace,
        kc::ENTER => KeyCode::Enter,
        kc::LEFT => KeyCode::Left,
        kc::RIGHT => KeyCode::Right,
        kc::UP => KeyCode::Up,
        kc::DOWN => KeyCode::Down,
        kc::HOME => KeyCode::Home,
        kc::END => KeyCode::End,
        kc::PAGE_UP => KeyCode::PageUp,
        kc::PAGE_DOWN => KeyCode::PageDown,
        kc::TAB => KeyCode::Tab,
        kc::BACKTAB => KeyCode::BackTab,
        kc::DELETE => KeyCode::Delete,
        kc::INSERT => KeyCode::Insert,
        kc::ESCAPE => KeyCode::Escape,
        kc::F1..=kc::F24 =>
        {
            #[allow(clippy::cast_possible_truncation)]
            KeyCode::F((code - kc::F1 + 1) as u8)
        }
        _ => KeyCode::Char(char::from_u32(code)?),
    };

    let mut modifiers = KeyModifiers::NONE;
    if mods & 0b001 != 0 {
        modifiers |= KeyModifiers::SHIFT;
    }
    if mods & 0b010 != 0 {
        modifiers |= KeyModifiers::CONTROL;
    }
    if mods & 0b100 != 0 {
        modifiers |= KeyModifiers::ALT;
    }
    if mods & 0b1000 != 0 {
        modifiers |= KeyModifiers::SUPER;
    }

    Some(retroglyph_core::event::KeyEvent::new(key_code, modifiers))
}

/// `code` values for [`decode_key_event`]'s named (non-printable) keys.
///
/// Values start at `0x0011_0000`, above the Unicode scalar value space
/// (`0x0..=0x10FFFF`), so a single `u32` can carry either a codepoint or a
/// named key without ambiguity.
pub mod key_codes {
    const BASE: u32 = 0x0011_0000;

    /// Backspace.
    pub const BACKSPACE: u32 = BASE;
    /// Enter.
    pub const ENTER: u32 = BASE + 1;
    /// Left arrow.
    pub const LEFT: u32 = BASE + 2;
    /// Right arrow.
    pub const RIGHT: u32 = BASE + 3;
    /// Up arrow.
    pub const UP: u32 = BASE + 4;
    /// Down arrow.
    pub const DOWN: u32 = BASE + 5;
    /// Home.
    pub const HOME: u32 = BASE + 6;
    /// End.
    pub const END: u32 = BASE + 7;
    /// Page Up.
    pub const PAGE_UP: u32 = BASE + 8;
    /// Page Down.
    pub const PAGE_DOWN: u32 = BASE + 9;
    /// Tab.
    pub const TAB: u32 = BASE + 10;
    /// Backtab (Shift+Tab).
    pub const BACKTAB: u32 = BASE + 11;
    /// Delete.
    pub const DELETE: u32 = BASE + 12;
    /// Insert.
    pub const INSERT: u32 = BASE + 13;
    /// Escape.
    pub const ESCAPE: u32 = BASE + 14;
    /// F1. F2-F24 follow contiguously up to [`F24`].
    pub const F1: u32 = BASE + 100;
    /// F24, the last of the contiguous F1-F24 range.
    pub const F24: u32 = F1 + 23;
}

/// The `wasm-bindgen`-exported FFI surface, compiled only for `wasm32`.
///
/// A thin, stateful wrapper around [`TerminalWasm`] keyed by opaque handles,
/// since `wasm-bindgen` cannot export a type generic enough to hand a
/// `TerminalWasm` (or a `Terminal<TerminalWasm>`) directly to arbitrary game
/// code the way `retroglyph_examples::rg_run!` does for the software
/// backend. Each example that wants a WASM/xterm.js demo drives its own
/// per-example `#[wasm_bindgen]` entry point (see
/// `crates/examples/src/util/mod.rs`'s `rg_run!` for the software
/// equivalent); this module only owns the terminal instance registry and
/// event decoding that every such entry point would otherwise duplicate.
#[cfg(target_arch = "wasm32")]
pub mod wasm {
    use super::{TerminalWasm, decode_key_event};
    use std::cell::RefCell;
    use std::collections::HashMap;
    use wasm_bindgen::prelude::wasm_bindgen;

    thread_local! {
        static INSTANCES: RefCell<HashMap<u32, TerminalWasm>> = RefCell::new(HashMap::new());
        static NEXT_HANDLE: RefCell<u32> = const { RefCell::new(1) };
    }

    /// Creates a new [`TerminalWasm`] of the given size and returns an opaque
    /// handle for use with the other `wasm_terminal_*` functions.
    #[wasm_bindgen]
    #[must_use]
    pub fn wasm_terminal_new(width: u16, height: u16) -> u32 {
        let handle = NEXT_HANDLE.with_borrow_mut(|next| {
            let handle = *next;
            *next += 1;
            handle
        });
        INSTANCES.with_borrow_mut(|instances| {
            instances.insert(handle, TerminalWasm::new(width, height));
        });
        handle
    }

    /// Destroys the [`TerminalWasm`] identified by `handle`, freeing its
    /// memory. Further calls with `handle` are no-ops.
    #[wasm_bindgen]
    pub fn wasm_terminal_free(handle: u32) {
        INSTANCES.with_borrow_mut(|instances| {
            instances.remove(&handle);
        });
    }

    /// Reports a new size (in cells) for the terminal identified by
    /// `handle`, e.g. after xterm.js's `fit` addon recomputes `cols`/`rows`.
    ///
    /// Logs a warning (via the `log` crate) and otherwise does nothing if
    /// `handle` is unknown, e.g. because the terminal was already freed via
    /// [`wasm_terminal_free`].
    #[wasm_bindgen]
    pub fn wasm_terminal_resize(handle: u32, width: u16, height: u16) {
        use retroglyph_core::backend::Backend;
        use retroglyph_core::grid::Size;
        INSTANCES.with_borrow_mut(|instances| {
            if let Some(term) = instances.get_mut(&handle) {
                term.resize(Size { width, height });
            } else {
                log::warn!("wasm_terminal_resize: unknown handle {handle}");
            }
        });
    }

    /// Pushes a key event into the terminal identified by `handle`. See
    /// [`decode_key_event`] for the `code`/`mods` encoding.
    ///
    /// Silently ignores codes that don't decode to a known key (e.g. a lone
    /// Unicode combining mark with no assigned scalar meaning here). Logs a
    /// warning (via the `log` crate) and otherwise does nothing if `handle`
    /// is unknown, e.g. because the terminal was already freed via
    /// [`wasm_terminal_free`].
    #[wasm_bindgen]
    pub fn wasm_terminal_push_key(handle: u32, code: u32, mods: u8) {
        use retroglyph_core::event::Event;
        let Some(key_event) = decode_key_event(code, mods) else {
            return;
        };
        INSTANCES.with_borrow_mut(|instances| {
            if let Some(term) = instances.get_mut(&handle) {
                term.push_event(Event::Key(key_event));
            } else {
                log::warn!("wasm_terminal_push_key: unknown handle {handle}");
            }
        });
    }

    /// Drains and returns the ANSI bytes rendered since the last call for the
    /// terminal identified by `handle`. Returns an empty string if `handle`
    /// is unknown or nothing has been drawn since the last call.
    ///
    /// Logs a warning (via the `log` crate) in the unknown-`handle` case;
    /// callers that only ever pass handles from [`wasm_terminal_new`] and
    /// stop using them after [`wasm_terminal_free`] should never see one.
    #[wasm_bindgen]
    #[must_use]
    pub fn wasm_terminal_take_output(handle: u32) -> String {
        INSTANCES.with_borrow_mut(|instances| {
            let Some(term) = instances.get_mut(&handle) else {
                log::warn!("wasm_terminal_take_output: unknown handle {handle}");
                return String::new();
            };
            term.take_output()
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use retroglyph_core::Terminal;
    use retroglyph_core::event::{Event, KeyCode, KeyModifiers};

    #[test]
    fn renders_into_pullable_buffer() {
        let backend = TerminalWasm::new(10, 3);
        let mut term = Terminal::new(backend);
        term.put(1, 1, 'H');
        term.present().unwrap();
        let out = term.backend_mut().take_output();
        assert!(out.contains('H'), "output: {out:?}");
        // Draining again returns nothing new until the next present().
        assert_eq!(term.backend_mut().take_output(), "");
    }

    #[test]
    fn push_event_then_poll_roundtrips() {
        let mut backend = TerminalWasm::new(10, 3);
        backend.push_event(Event::Key(retroglyph_core::event::KeyEvent::new(
            KeyCode::Left,
            KeyModifiers::NONE,
        )));
        assert_eq!(
            Backend::poll_event(&mut backend, Duration::ZERO),
            Some(Event::Key(retroglyph_core::event::KeyEvent::new(
                KeyCode::Left,
                KeyModifiers::NONE
            )))
        );
        assert_eq!(Backend::poll_event(&mut backend, Duration::ZERO), None);
    }

    #[test]
    fn cursor_position_uses_1_indexed_cup_sequence() {
        // CSI row;col H (CUP), 1-indexed and absolute: verified against
        // xterm.js and hterm/Terminalemulator (see `write_cursor_position`'s
        // doc comment). Both use the same format, so no dual-emission or
        // 0-indexed fallback is needed.
        let mut backend = TerminalWasm::new(10, 3);
        Backend::set_cursor_position(&mut backend, Pos { x: 0, y: 0 });
        assert_eq!(backend.take_output(), "\x1b[1;1H");

        Backend::set_cursor_position(&mut backend, Pos { x: 4, y: 2 });
        assert_eq!(backend.take_output(), "\x1b[3;5H");
    }

    #[test]
    fn size_is_set_externally_not_queried() {
        let mut backend = TerminalWasm::new(80, 24);
        assert_eq!(
            backend.size(),
            Size {
                width: 80,
                height: 24
            }
        );
        backend.resize(Size {
            width: 40,
            height: 12,
        });
        assert_eq!(
            backend.size(),
            Size {
                width: 40,
                height: 12
            }
        );
    }

    #[test]
    fn decode_key_event_maps_printable_char() {
        let key = decode_key_event(u32::from('a'), 0).unwrap();
        assert_eq!(key.code, KeyCode::Char('a'));
        assert!(key.modifiers.is_empty());
    }

    #[test]
    fn decode_key_event_maps_named_keys() {
        let key = decode_key_event(key_codes::LEFT, 0b010).unwrap();
        assert_eq!(key.code, KeyCode::Left);
        assert!(key.modifiers.contains(KeyModifiers::CONTROL));
    }

    #[test]
    fn decode_key_event_maps_super_modifier() {
        let key = decode_key_event(u32::from('x'), 0b1000).unwrap();
        assert_eq!(key.code, KeyCode::Char('x'));
        assert!(key.modifiers.contains(KeyModifiers::SUPER));
    }

    #[test]
    fn decode_key_event_maps_super_combined_with_other_modifiers() {
        let key = decode_key_event(u32::from('x'), 0b1011).unwrap();
        assert!(key.modifiers.contains(KeyModifiers::SHIFT));
        assert!(key.modifiers.contains(KeyModifiers::CONTROL));
        assert!(key.modifiers.contains(KeyModifiers::SUPER));
        assert!(!key.modifiers.contains(KeyModifiers::ALT));
    }

    #[test]
    fn decode_key_event_maps_function_keys() {
        let key = decode_key_event(key_codes::F1, 0).unwrap();
        assert_eq!(key.code, KeyCode::F(1));

        let key = decode_key_event(key_codes::F1 + 11, 0).unwrap();
        assert_eq!(key.code, KeyCode::F(12));
    }

    // Guards against the JS driver example silently forking into two different (and eventually
    // contradictory) versions: one embedded in this crate's own doc comment (via `include_str!`
    // of `js/xterm-driver.js`, see the module doc above) and one hand-copied into README.md's
    // "Usage from JS" section, since crates.io/GitHub render README.md as plain markdown and
    // can't `include_str!` it the way rustdoc can. `js/xterm-driver.js` is the source of truth;
    // if this test fails, README.md's fenced ```js block fell out of sync with it.
    #[test]
    fn readme_js_example_matches_canonical_driver() {
        let canonical = include_str!("../js/xterm-driver.js");
        let readme = include_str!("../README.md");

        let fence_start = readme
            .find("```js\n")
            .expect("README.md should have a ```js fenced code block")
            + "```js\n".len();
        let fence_end = readme[fence_start..]
            .find("```")
            .expect("README.md's ```js fence should be closed")
            + fence_start;
        let readme_js = &readme[fence_start..fence_end];

        assert_eq!(
            readme_js, canonical,
            "README.md's JS driver example has drifted from js/xterm-driver.js -- update \
             README.md's fenced ```js block to match the canonical file"
        );
    }
}
