[package]
name = "retroglyph"
edition = "2024"
license = "MIT"

description = "2D pseudographic terminal"
repository = "https://github.com/crates-lurey-io/retroglyph"
version = "0.0.0-reserved"

[lints.clippy]
pedantic = "deny"

[dependencies]

[dev-dependencies]
raw-window-handle = "0.6.2"
softbuffer = "0.4.6"
winit = "0.30.11"

[workspace]
members = ["tools/cargo-bin"]

[workspace.metadata.bin]
cargo-nextest = { version = "0.9.98", locked = true }
cargo-llvm-cov = { version = "0.6.16", locked = true }
just = { version = "1.40.0" }
taplo-cli = { version = "0.10.0", bins = ["taplo"] }
