codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flags:
  core:
    paths:
      - crates/core/src/
    carryforward: true
  terminal:
    paths:
      - crates/terminal/src/
    carryforward: true
  crossterm:
    paths:
      - crates/crossterm/src/
    carryforward: true
  terminal-wasm:
    paths:
      - crates/terminal-wasm/src/
    carryforward: true
  software:
    paths:
      - crates/software/src/
    carryforward: true
  window:
    paths:
      - crates/window/src/
    carryforward: true
  widgets:
    paths:
      - crates/widgets/src/
    carryforward: true

comment:
  layout: condensed_header, condensed_files, condensed_footer
  behavior: default
  require_changes: true
