#![allow(dead_code, unreachable_pub)]
//! Hex board game replay demo.
//!
//! Visualises a scripted scenario with a hex grid map, unit markers, a
//! styled event-log sidebar, faction card hands, and step-by-step playback
//! controls.
//!
//! Run (software renderer, required for sprite tiles):
//!   `cargo run --example hex_battle --features software-tilesets,software-default-font`
//!
//! The crossterm fallback uses colored-block hex cells instead of PNG sprites.
//!
//! Controls:
//!   ← / H         – previous step
//!   → / L / Space – advance one step
//!   Q / Esc       – quit

mod hexmap;
mod render;
mod sim;

#[cfg(feature = "tilesets")]
use render::{MAP_COLS, MAP_ROWS};
use render::{RenderState, render_frame};
use retroglyph_core::Backend;
use retroglyph_core::Terminal;
use retroglyph_core::event::{Event, KeyCode, MouseButton, MouseEventKind};
use sim::ReplayStep;
use std::time::Duration;

// ── Tileset sprite sheet path (generated by build.rs) ────────────────────────

#[cfg(feature = "tilesets")]
static HEX_SPRITE_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/hex_sprites.png"));

// ── State ─────────────────────────────────────────────────────────────────────

struct State {
    steps: Vec<ReplayStep>,
    current: usize,
    render: RenderState,
}

// ── Initialisation ────────────────────────────────────────────────────────────

fn init<B: Backend>(_term: &mut Terminal<B>) -> State {
    let (_, steps) = sim::build_scenario();
    let total = steps.len();
    State {
        steps,
        current: 0,
        render: RenderState {
            hovered: None,
            step: 0,
            total_steps: total,
        },
    }
}

// ── Game tick ─────────────────────────────────────────────────────────────────

fn tick<B: Backend>(term: &mut Terminal<B>, state: &mut State) -> bool {
    let timeout = Duration::from_millis(50);
    while let Some(event) = term.poll(timeout) {
        match event {
            Event::Key(k) if k.is_down() => match k.code {
                KeyCode::Char('q') | KeyCode::Escape => return false,
                KeyCode::Right | KeyCode::Char('l' | ' ') => {
                    if state.current + 1 < state.steps.len() {
                        state.current += 1;
                        state.render.step = state.current;
                    }
                }
                KeyCode::Left | KeyCode::Char('h') if state.current > 0 => {
                    state.current -= 1;
                    state.render.step = state.current;
                }
                _ => {}
            },
            Event::Mouse(m) => {
                let hovered = hexmap::cell_to_axial(m.position.x, m.position.y);
                state.render.hovered = hovered;

                if m.kind == MouseEventKind::Down(MouseButton::Left)
                    && state.current + 1 < state.steps.len()
                {
                    state.current += 1;
                    state.render.step = state.current;
                }
            }
            Event::Close => return false,
            Event::Key(_) | Event::Resize(..) => {}
        }
    }

    let step = &state.steps[state.current];
    render_frame(term, step, &state.render, &state.steps);
    let _ = term.present();
    true
}

// ── Entry points ──────────────────────────────────────────────────────────────

#[cfg(feature = "tilesets")]
retroglyph_examples::rg_run_software!(
    State,
    init,
    tick,
    builder = {
        use retroglyph_software::SoftwareBackendBuilder;
        use retroglyph_software::tileset::{Codepage, TilesetOptions};
        let hex_tileset = TilesetOptions::from_bytes(HEX_SPRITE_BYTES.to_vec())
            .tile_size(32, 32)
            .codepage(Codepage::Identity)
            .spacing(hexmap::HEX_CELL_COLS, hexmap::HEX_CELL_ROWS)
            .build()
            .expect("hex tileset build failed");
        SoftwareBackendBuilder::new()
            .title("Hex Battle — Replay")
            .grid_size(MAP_COLS + 50, MAP_ROWS + 4)
            .scale(2)
            .target_fps(30)
            .tileset(hex_tileset)
    }
);

#[cfg(all(feature = "crossterm", not(feature = "tilesets")))]
retroglyph_examples::rg_run!(State, init, tick);

// Neither pixel-rendered sprites nor an ASCII-art terminal are available;
// fall back to a headless smoke run (see `examples/runner.rs`'s Headless option).
#[cfg(not(any(feature = "tilesets", feature = "crossterm")))]
fn main() {
    retroglyph_examples::util::run_headless(init, tick);
}
