#![allow(dead_code, unreachable_pub)]
//! Hex board game replay demo.
//!
//! Visualises a scripted scenario with a hex grid map, unit markers, a
//! styled event-log sidebar, faction card hands, and step-by-step playback
//! controls.
//!
//! Run (software renderer, required for sprite tiles):
//!   `cargo run --example hex_battle --features software-tilesets,software-default-font`
//!
//! The crossterm fallback uses colored-block hex cells instead of PNG sprites.
//!
//! Controls:
//!   ← / H         – previous step
//!   → / L / Space – advance one step
//!   Q / Esc       – quit

mod hexmap;
mod render;
mod sim;

#[cfg(feature = "tilesets")]
use render::{MAP_COLS, MAP_ROWS};
use render::{RenderState, render_frame};
use retroglyph_core::Backend;
use retroglyph_core::Terminal;
use retroglyph_core::event::{Event, KeyCode, MouseButton, MouseEventKind};
use sim::ReplayStep;
use std::time::Duration;

// ── Tileset sprite sheet path (generated by build.rs) ────────────────────────

#[cfg(feature = "tilesets")]
static HEX_SPRITE_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/hex_sprites.png"));

// ── State ─────────────────────────────────────────────────────────────────────

struct State {
    steps: Vec<ReplayStep>,
    current: usize,
    render: RenderState,
}

// ── Initialisation ────────────────────────────────────────────────────────────

fn init<B: Backend>(_term: &mut Terminal<B>) -> State {
    let (_, steps) = sim::build_scenario();
    let total = steps.len();
    State {
        steps,
        current: 0,
        render: RenderState {
            hovered: None,
            step: 0,
            total_steps: total,
        },
    }
}

// ── Game tick ─────────────────────────────────────────────────────────────────

fn tick<B: Backend>(term: &mut Terminal<B>, state: &mut State) -> bool {
    let timeout = Duration::from_millis(50);
    while let Some(event) = term.poll(timeout) {
        match event {
            Event::Key(k) if k.is_down() => match k.code {
                KeyCode::Char('q') | KeyCode::Escape => return false,
                KeyCode::Right | KeyCode::Char('l' | ' ') => {
                    if state.current + 1 < state.steps.len() {
                        state.current += 1;
                        state.render.step = state.current;
                    }
                }
                KeyCode::Left | KeyCode::Char('h') if state.current > 0 => {
                    state.current -= 1;
                    state.render.step = state.current;
                }
                _ => {}
            },
            Event::Mouse(m) => {
                let hovered = hexmap::cell_to_axial(m.position.x, m.position.y);
                state.render.hovered = hovered;

                if m.kind == MouseEventKind::Down(MouseButton::Left)
                    && state.current + 1 < state.steps.len()
                {
                    state.current += 1;
                    state.render.step = state.current;
                }
            }
            Event::Close => return false,
            Event::Key(_) | Event::Resize(..) | Event::ThemeChanged(_) => {}
        }
    }

    let step = &state.steps[state.current];
    render_frame(term, step, &state.render, &state.steps);
    let _ = term.present();
    true
}

// ── Entry points ──────────────────────────────────────────────────────────────

#[cfg(feature = "tilesets")]
retroglyph_examples::rg_run_software!(
    State,
    init,
    tick,
    builder = {
        use retroglyph_software::SoftwareBackendBuilder;
        use retroglyph_software::tileset::{Codepage, TilesetOptions};
        let hex_tileset = TilesetOptions::from_bytes(HEX_SPRITE_BYTES.to_vec())
            .tile_size(32, 32)
            .codepage(Codepage::Identity)
            .spacing(hexmap::HEX_CELL_COLS, hexmap::HEX_CELL_ROWS)
            .build()
            .expect("hex tileset build failed");
        SoftwareBackendBuilder::new()
            .title("Hex Battle — Replay")
            .grid_size(MAP_COLS + 50, MAP_ROWS + 4)
            .scale(2)
            .target_fps(30)
            .tileset(hex_tileset)
    }
);

#[cfg(all(feature = "crossterm", not(feature = "tilesets")))]
retroglyph_examples::rg_run!(State, init, tick);

// WASM Headless backend (browser rAF loop, no canvas/window): same shared
// arm `rg_run!`/`rg_run_software!` use internally, called directly here
// since hex_battle hand-rolls its own four-way dispatch instead of going
// through either macro. Takes priority over the stdout fallback below, but
// yields to `tilesets` (software) if both are somehow enabled at once.
//
// Note this arm keys on `tilesets` rather than `software` (unlike the
// shared macros' internal gate, which keys on `software`) because
// hex_battle's own `rg_run_software!` call site above is itself gated on
// `tilesets`, not `software` directly -- keeping the two in lockstep here
// avoids a "no main found" gap for a `software`-without-`tilesets` build,
// which isn't a combination hex_battle otherwise supports.
#[cfg(not(feature = "tilesets"))]
retroglyph_examples::__rg_wasm_headless_arm!(State, init, tick);

// WASM Terminal backend (xterm.js, no canvas/window): same shared arm as
// above, mirroring the wasm-headless arm's rationale -- keyed on `tilesets`
// (not `software`) to stay in lockstep with the `rg_run_software!` call site
// above. The macro's own internal `not(any(software, wasm-headless))` guard
// (see `__rg_wasm_terminal_arm!`'s doc comment) handles yielding to those two
// if either is somehow enabled at once, same as the wasm-headless arm above
// relies on `__rg_wasm_headless_arm!`'s internal `not(feature = "software")`.
#[cfg(not(feature = "tilesets"))]
retroglyph_examples::__rg_wasm_terminal_arm!(State, init, tick);

// Neither pixel-rendered sprites, an ASCII-art terminal, nor the wasm
// Headless/Terminal backends are available; fall back to a headless smoke
// run (see `examples/runner.rs`'s Headless option).
#[cfg(not(any(
    feature = "tilesets",
    feature = "crossterm",
    all(feature = "wasm-headless", target_arch = "wasm32"),
    all(feature = "wasm-terminal", target_arch = "wasm32"),
)))]
fn main() {
    retroglyph_examples::util::run_headless(init, tick);
}
