#![allow(dead_code, unreachable_pub)]
//! Battle for Hoth-style hex board game replay demo.
//!
//! Visualises a pre-baked scenario with a hex grid map, unit markers, a
//! styled event-log sidebar, faction card hands, and step-by-step playback
//! controls.
//!
//! Run (software renderer, required):
//!   `cargo run --example hex_battle --features software-tilesets,software-default-font`
//!
//! The crossterm fallback uses ASCII art hexes instead of PNG sprites.
//!
//! Controls:
//!   ← / H       – previous step
//!   → / L / Space – advance one step
//!   Q / Esc      – quit

mod hexmap;
mod render;
mod sim;

// Brings rg_run!, rg_run_software!, and draw utilities into scope.
#[path = "../util/mod.rs"]
mod util;

use render::{MAP_COLS, MAP_ROWS, RenderState, render_frame};
use retroglyph::Terminal;
use retroglyph::backend::Backend;
use retroglyph::event::{Event, KeyCode, MouseButton, MouseEventKind};
use sim::ReplayStep;
use std::time::Duration;

// ── Tileset sprite sheet path (generated by build.rs) ────────────────────────

#[cfg(feature = "software-tilesets")]
static HEX_SPRITE_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/hex_sprites.png"));

// ── State ─────────────────────────────────────────────────────────────────────

struct State {
    steps: Vec<ReplayStep>,
    current: usize,
    render: RenderState,
}

// ── Initialisation ────────────────────────────────────────────────────────────

fn init<B: Backend>(_term: &mut Terminal<B>) -> State {
    let (_, steps) = sim::build_scenario();
    let total = steps.len();
    State {
        steps,
        current: 0,
        render: RenderState {
            hovered: None,
            step: 0,
            total_steps: total,
        },
    }
}

// ── Game tick ─────────────────────────────────────────────────────────────────

fn tick<B: Backend>(term: &mut Terminal<B>, state: &mut State) -> bool {
    let timeout = Duration::from_millis(50);
    while let Some(event) = term.poll(timeout) {
        match event {
            Event::Key(k) => match k.code {
                KeyCode::Char('q') | KeyCode::Escape => return false,
                KeyCode::Right | KeyCode::Char('l' | ' ') => {
                    if state.current + 1 < state.steps.len() {
                        state.current += 1;
                        state.render.step = state.current;
                    }
                }
                KeyCode::Left | KeyCode::Char('h') if state.current > 0 => {
                    state.current -= 1;
                    state.render.step = state.current;
                }
                _ => {}
            },
            Event::Mouse(m) => {
                // Both paths ultimately map to cell coordinates. The
                // pixel_position (software backend) gives sub-cell precision;
                // for crossterm we fall back to the already-converted cell pos.
                // Cell-based lookup is accurate enough for a 3×2-cell-per-hex grid.
                let hovered = hexmap::cell_to_axial(m.position.x, m.position.y);
                state.render.hovered = hovered;

                if m.kind == MouseEventKind::Down(MouseButton::Left) {
                    // Click: advance replay.
                    if state.current + 1 < state.steps.len() {
                        state.current += 1;
                        state.render.step = state.current;
                    }
                }
            }
            Event::Close => return false,
            Event::Resize(..) => {}
        }
    }

    let step = &state.steps[state.current];
    render_frame(term, step, &state.render, &state.steps);
    let _ = term.present();
    true
}

// ── Entry points ──────────────────────────────────────────────────────────────
//
// Software path: custom builder (tileset registration) via rg_run_software!.
// Crossterm path: standard rg_run! crossterm arm.

#[cfg(feature = "software-tilesets")]
crate::rg_run_software!(
    State,
    init,
    tick,
    builder = {
        use retroglyph::backend::software::SoftwareBackendBuilder;
        use retroglyph::backend::software::tileset::{Codepage, TilesetOptions};
        let hex_tileset = TilesetOptions::from_bytes(HEX_SPRITE_BYTES.to_vec())
            .tile_size(64, 64)
            .codepage(Codepage::Identity)
            .spacing(hexmap::HEX_CELL_COLS, hexmap::HEX_CELL_ROWS)
            .build()
            .expect("hex tileset build failed");
        SoftwareBackendBuilder::new()
            .title("Battle for Hoth — Simulator Replay")
            .grid_size(MAP_COLS + 36, MAP_ROWS + 4)
            .scale(2)
            .target_fps(30)
            .tileset(hex_tileset)
    }
);

#[cfg(all(feature = "crossterm", not(feature = "software-tilesets")))]
crate::rg_run!(State, init, tick);

#[cfg(not(any(feature = "software-tilesets", feature = "crossterm")))]
compile_error!(
    "hex_battle requires `software-tilesets` (preferred) or `crossterm`.\n\
     Run with: --features software-tilesets,software-default-font"
);
