//! Interactive gallery runner.
//!
//! 1. Pick an example -- auto-discovered from `examples/*.rs`, no list to maintain by hand.
//! 2. Pick a backend -- every example supports all four, since they're all generated by
//!    [`rg_gallery_run!`](retroglyph_gallery::rg_gallery_run).
//! 3. Launches `cargo run` with the correct feature flags.
//!
//! Discovery convention: any `NN_snake_case.rs` file in this directory is an example (`runner.rs`
//! itself is excluded by not matching that pattern). Its one-line description comes from the
//! first line of its module doc comment, which must be of the form:
//!
//! ```text
//! //! NN: Title -- one-line description
//! ```
//!
//! The `-- description` suffix is what's shown in the picker; see any `NN_*.rs` file's first
//! line for the convention in practice.
//!
//! Deliberately minimal for now: the WASM option just shells out to `cargo run --target
//! wasm32-unknown-unknown` (relying on `.cargo/config.toml`'s `wasm-server-runner` runner) rather
//! than the fuller docs-parity preview (build + wasm-bindgen + serve + open browser)
//! `crates/examples/examples/runner.rs` does -- and there's no `--manifest` flag for CI yet,
//! either.
//!
//! Run with: `cargo run --example runner`

use std::io::{self, BufRead, Write};
use std::os::unix::process::CommandExt;
use std::path::Path;
use std::process::Command;

// ── Backend ───────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq)]
enum Backend {
    Terminal,
    Desktop,
    Wasm,
    Headless,
}

impl Backend {
    const ALL: &'static [Self] = &[Self::Terminal, Self::Desktop, Self::Wasm, Self::Headless];

    const fn label(self) -> &'static str {
        match self {
            Self::Terminal => "Terminal",
            Self::Desktop => "Desktop",
            Self::Wasm => "WASM",
            Self::Headless => "Headless",
        }
    }

    const fn summary(self) -> &'static str {
        match self {
            Self::Terminal => "runs in this shell",
            Self::Desktop => "native window",
            Self::Wasm => "browser tab (via wasm-server-runner)",
            Self::Headless => "no display -- prints a few frames to stdout",
        }
    }

    const fn features(self) -> &'static [&'static str] {
        match self {
            Self::Terminal => &["crossterm"],
            Self::Desktop | Self::Wasm => &["default-font"],
            // No feature: examples fall back to the Headless backend when
            // neither crossterm nor software is enabled.
            Self::Headless => &[],
        }
    }

    const fn target(self) -> Option<&'static str> {
        match self {
            Self::Wasm => Some("wasm32-unknown-unknown"),
            Self::Terminal | Self::Desktop | Self::Headless => None,
        }
    }
}

// ── Example discovery ──────────────────────────────────────────────────────

struct Example {
    name: String,
    description: String,
}

impl Example {
    /// `name` without its `NN_` ordering prefix, for display -- the menu's own index already
    /// conveys the number, so showing it twice (`1) 01_hello_world`) is pure noise.
    fn display_name(&self) -> &str {
        // `is_example_filename` (the only way an `Example` gets constructed) guarantees `name`
        // starts with two ASCII digits and an underscore.
        &self.name[3..]
    }
}

/// A file name counts as an example if it's `NN_*.rs` -- two ASCII digits, an underscore, then
/// anything. This excludes `runner.rs` (and any other non-numbered helper file) without an
/// explicit exclude list to maintain.
fn is_example_filename(name: &str) -> bool {
    let bytes = name.as_bytes();
    Path::new(name)
        .extension()
        .is_some_and(|ext| ext.eq_ignore_ascii_case("rs"))
        && bytes.len() > 3
        && bytes[0].is_ascii_digit()
        && bytes[1].is_ascii_digit()
        && bytes[2] == b'_'
}

/// Pulls the `-- description` suffix off an example file's first doc-comment line.
///
/// Expects `//! NN: Title -- description`; falls back to the whole line (minus the `//! `
/// prefix) if no ` -- ` separator is present, so a missing convention degrades to something
/// still readable instead of an empty description.
fn parse_description(source: &str) -> String {
    let Some(first_line) = source.lines().find_map(|line| line.strip_prefix("//!")) else {
        return String::new();
    };
    let first_line = first_line.trim();
    match first_line.split_once(" -- ") {
        Some((_title, description)) => description.trim().to_owned(),
        None => first_line.to_owned(),
    }
}

/// Scans this file's own directory for `NN_*.rs` files and reads each one's description.
///
/// Uses `CARGO_MANIFEST_DIR` (baked in at compile time) rather than the process's current
/// directory, so this works regardless of where `cargo run --example runner` is invoked from.
fn discover_examples() -> Vec<Example> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("examples");
    let mut examples: Vec<Example> = std::fs::read_dir(&dir)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let file_name = entry.file_name();
            let file_name = file_name.to_str()?;
            is_example_filename(file_name).then(|| {
                let source = std::fs::read_to_string(entry.path())
                    .unwrap_or_else(|err| panic!("failed to read {file_name}: {err}"));
                Example {
                    name: file_name.trim_end_matches(".rs").to_owned(),
                    description: parse_description(&source),
                }
            })
        })
        .collect();
    examples.sort_by(|a, b| a.name.cmp(&b.name));
    examples
}

// ── I/O helpers ─────────────────────────────────────────────────────────────

fn prompt(msg: &str) -> String {
    print!("{msg}");
    io::stdout().flush().unwrap();
    let mut buf = String::new();
    io::stdin().lock().read_line(&mut buf).unwrap();
    buf.trim().to_owned()
}

/// Prints `items` as a numbered `  N) primary -- secondary` menu -- column-aligned, so every
/// `--` lines up regardless of how long each `primary` is -- then reprompts until the user picks
/// a valid `1..=items.len()`. Shared between the example and backend pickers below, which were
/// previously two separately hand-rolled copies of the same print-then-reprompt loop.
fn pick<T>(
    prompt_label: &str,
    items: &[T],
    primary: impl Fn(&T) -> &str,
    secondary: impl Fn(&T) -> &str,
) -> usize {
    let index_width = items.len().to_string().len();
    let name_width = items
        .iter()
        .map(|item| primary(item).len())
        .max()
        .unwrap_or(0);
    for (i, item) in items.iter().enumerate() {
        println!(
            "  {:>index_width$}) {:<name_width$} -- {}",
            i + 1,
            primary(item),
            secondary(item)
        );
    }

    loop {
        let input = prompt(&format!("\n{prompt_label} [1-{}]: ", items.len()));
        match input.parse::<usize>() {
            Ok(n) if n >= 1 && n <= items.len() => return n - 1,
            _ => println!("  Invalid choice."),
        }
    }
}

// ── Launch ──────────────────────────────────────────────────────────────────

fn launch(ex: &Example, backend: Backend) -> ! {
    let features = backend.features();

    println!("\n  Launching: {}", ex.name);
    if !features.is_empty() {
        println!("  Features:  {}", features.join(","));
    }
    if let Some(target) = backend.target() {
        println!("  Target:    {target}");
    }
    println!();

    let mut cmd = Command::new("cargo");
    cmd.args(["run", "--example", &ex.name]);
    if !cfg!(debug_assertions) {
        cmd.arg("--release");
    }
    if !features.is_empty() {
        cmd.args(["--features", &features.join(",")]);
    }
    if let Some(target) = backend.target() {
        cmd.args(["--target", target]);
    }

    let err = cmd.exec();
    eprintln!("  Failed to exec: {err}");
    std::process::exit(1);
}

// ── Main ──────────────────────────────────────────────────────────────────

fn main() {
    let examples = discover_examples();
    assert!(!examples.is_empty(), "no NN_*.rs examples found");

    println!("retroglyph gallery\n");
    let choice = pick("Pick an example", &examples, Example::display_name, |ex| {
        ex.description.as_str()
    });
    let ex = &examples[choice];

    println!();
    let backend = Backend::ALL[pick(
        "Pick a backend",
        Backend::ALL,
        |b| b.label(),
        |b| b.summary(),
    )];

    launch(ex, backend);
}
