[store]
dir = "target/nextest"

[profile.default]
fail-fast = false
slow-timeout = { period = "20s", terminate-after = 2 }

[profile.ci]
fail-fast = false
slow-timeout = { period = "20s", terminate-after = 2 }
junit = { path = "junit.xml" }
